version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: crudlapisco/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=senhapostgre
      - POSTGRES_USER=userpostgre
      - POSTGRES_DB=nomebanco
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}